
import { WebsiteListing } from './types';

export const MOCK_LISTINGS: WebsiteListing[] = [
  {
    id: '1',
    name: 'SaaSly Analytics',
    url: 'https://saasly-analytics.io',
    description: 'A comprehensive analytics dashboard for early-stage SaaS companies with 150+ active paid users.',
    category: 'SaaS',
    price: 45000,
    monthlyRevenue: 2800,
    monthlyProfit: 2200,
    monthlyTraffic: 15000,
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Tailwind'],
    image: 'https://picsum.photos/seed/saas/800/450',
    age: '2 years',
    askingMultiple: 16.07,
    performance: [
      { month: 'Jan', revenue: 2100, visitors: 11000 },
      { month: 'Feb', revenue: 2250, visitors: 11500 },
      { month: 'Mar', revenue: 2400, visitors: 12200 },
      { month: 'Apr', revenue: 2550, visitors: 13000 },
      { month: 'May', revenue: 2700, visitors: 14200 },
      { month: 'Jun', revenue: 2800, visitors: 15000 },
    ]
  },
  {
    id: '2',
    name: 'EcoShop Pro',
    url: 'https://ecoshop-organic.com',
    description: 'Dropshipping marketplace specializing in sustainable and biodegradable kitchenware.',
    category: 'E-commerce',
    price: 12500,
    monthlyRevenue: 4500,
    monthlyProfit: 1200,
    monthlyTraffic: 45000,
    techStack: ['Shopify', 'Liquid', 'Meta Ads'],
    image: 'https://picsum.photos/seed/shop/800/450',
    age: '1 year',
    askingMultiple: 10.42,
    performance: [
      { month: 'Jan', revenue: 3800, visitors: 35000 },
      { month: 'Feb', revenue: 3900, visitors: 36000 },
      { month: 'Mar', revenue: 4100, visitors: 39000 },
      { month: 'Apr', revenue: 4200, visitors: 41000 },
      { month: 'May', revenue: 4400, visitors: 43000 },
      { month: 'Jun', revenue: 4500, visitors: 45000 },
    ]
  },
  {
    id: '3',
    name: 'DevTool Helper',
    url: 'https://devtool-helper.net',
    description: 'A suite of online utilities for developers including regex testers, formatters, and unit converters.',
    category: 'Tool',
    price: 8500,
    monthlyRevenue: 400,
    monthlyProfit: 350,
    monthlyTraffic: 120000,
    techStack: ['Next.js', 'Vercel', 'AdSense'],
    image: 'https://picsum.photos/seed/tool/800/450',
    age: '3 years',
    askingMultiple: 24.28,
    performance: [
      { month: 'Jan', revenue: 320, visitors: 95000 },
      { month: 'Feb', revenue: 330, visitors: 98000 },
      { month: 'Mar', revenue: 350, visitors: 105000 },
      { month: 'Apr', revenue: 370, visitors: 110000 },
      { month: 'May', revenue: 380, visitors: 115000 },
      { month: 'Jun', revenue: 400, visitors: 120000 },
    ]
  },
  {
    id: '4',
    name: 'Nomad Bites',
    url: 'https://nomadbites.blog',
    description: 'Niche authority travel blog focused on digital nomad food guides in SE Asia.',
    category: 'Content',
    price: 22000,
    monthlyRevenue: 1200,
    monthlyProfit: 1100,
    monthlyTraffic: 65000,
    techStack: ['WordPress', 'SEO', 'Affiliate Marketing'],
    image: 'https://picsum.photos/seed/nomad/800/450',
    age: '4 years',
    askingMultiple: 20.00,
    performance: [
      { month: 'Jan', revenue: 950, visitors: 52000 },
      { month: 'Feb', revenue: 1000, visitors: 55000 },
      { month: 'Mar', revenue: 1050, visitors: 58000 },
      { month: 'Apr', revenue: 1100, visitors: 61000 },
      { month: 'May', revenue: 1150, visitors: 63000 },
      { month: 'Jun', revenue: 1200, visitors: 65000 },
    ]
  },
    {
    id: '5',
    name: 'QuickHire API',
    url: 'https://quickhire-api.io',
    description: 'REST API for generating realistic mock HR data for enterprise testing environments.',
    category: 'SaaS',
    price: 32000,
    monthlyRevenue: 1500,
    monthlyProfit: 1400,
    monthlyTraffic: 8000,
    techStack: ['Go', 'Redis', 'Docker'],
    image: 'https://picsum.photos/seed/api/800/450',
    age: '1.5 years',
    askingMultiple: 22.85,
    performance: [
      { month: 'Jan', revenue: 1100, visitors: 5000 },
      { month: 'Feb', revenue: 1200, visitors: 5500 },
      { month: 'Mar', revenue: 1250, visitors: 6000 },
      { month: 'Apr', revenue: 1350, visitors: 6800 },
      { month: 'May', revenue: 1450, visitors: 7400 },
      { month: 'Jun', revenue: 1500, visitors: 8000 },
    ]
  }
];
